services:
  chipyard:
    image: locnguyen96/chipyard-dev:latest
    container_name: chipyard
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      - RISCV=/opt/riscv
      - JAVA_HEAP_SIZE=8G
      - PATH=/opt/riscv/bin:/opt/verilator/bin:/opt/firtool/bin:/usr/local/bin:/usr/bin:/bin
      - LD_LIBRARY_PATH=/opt/riscv/lib:/opt/firtool/lib
